name: CI

on:
    push:
        branches:
            - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install Dependencies
      run: npm install sfdx-cli
    - name: 'Populate auth file with DEVHUB_SFDX_URL secret'
      shell: bash
      run: 'echo ${{ secrets.SALESFORCE_AUTH_URL}} > ./SALESFORCE_AUTH_URL.txt'
    - name: 'Authenticate Dev Hub'
      run: 'sfdx force:auth:sfdxurl:store -f ./SALESFORCE_AUTH_URL.txt -a devhub -d'  
    - name: Create Scratch Org
      run: 'sfdx force:org:create -f config/project-scratch-def.json -a scratch-org -s -d 1'
    - name: Deploy source
      run: 'sfdx force:source:push'
    - name: Run Apex test
      run: 'sfdx force:apex:test:run -c -r human -d ./tests/apex -w 20'
    - name: 'Upload code coverage for Apex to Codecov.io'
      uses: codecov/codecov-action@v1
      with:
          flags: Apex
    - name: Delete Scratch Org
      run: 'sfdx force:org:delete -p -u scratch-org'